### ISSUE TITLE
I can't  Upload

### ISSUE THREAD

**Issue by buzhixihuan2021** [Drexel2k/VidUp#7]
I can use YouTube Studio Upload (chrome)。

I can't use VidUp.Setup.1.11.2  Upload .
![123](https://user-images.githubusercontent.com/91567826/146164387-1018b3f4-755c-4db2-b2dd-0687fe290fb8.jpg)

**Comment by Drexel2k** [comment]
I assume this a temporary API or internet connection problem, try again in a few hours. As you can read in the error there are connection and timeout issues. One video did succeed already I can see on the screenshot, I don't think it's a general problem with the app.

Let me know if the problem still exists tomorrow.

**Comment by buzhixihuan2021** [comment]
2021/12/7   succeed

2021/12/14-- 15--16     3 day  can't   Upload .

**Comment by Drexel2k** [comment]
Hm, it looks für me like a local connection problem. Do you use any proxy? Maybe reset the upload totally, it is resuming the upload. Context Button->Reset until state is Ready For Upload again.

Please enable tracing in the settings and send me a trace from documents->VidUp folder.

**Comment by buzhixihuan2021** [comment]
17.12.21 16:08:44.354: MainWindow.fileDrop: Start.
17.12.21 16:08:44.357: MainWindow.fileDrop: Dropped 1 files.
17.12.21 16:08:44.357: UploadListViewModel.AddFiles: Start, add 1 uploads.
17.12.21 16:08:44.358: UploadList.AddFiles: Start, add 1 files to uploads.
17.12.21 16:08:44.358: UploadList.AddFiles: Add 'F:\常用软件\新建文件夹 (3)\第二TD.flv'.
17.12.21 16:08:44.359: UploadList.AddFiles: No template found for upload, try to get default template.
17.12.21 16:08:44.359: UploadList.AddFiles: Default template '1' found.
17.12.21 16:08:44.446: UploadList.AddFiles: End.
17.12.21 16:08:44.446: UploadListViewModel.AddUploads: At least one template was auto added.
17.12.21 16:08:44.488: UploadListViewModel.AddUploads: End.
17.12.21 16:08:44.488: MainWindow.fileDrop: End.
17.12.21 16:09:08.448: Uploader.Upload: Start with resumeUploads: True, maxUploadInBytesPerSecond: 0.
17.12.21 16:09:08.464: YoutubeVideoUploadService.Upload: Start with upload: F:\常用软件\新建文件夹 (3)\第二TD.flv, maxUploadInBytesPerSecond: 0.
17.12.21 16:09:08.464: YoutubeVideoUploadService.Upload: Initialize upload.
17.12.21 16:09:08.464: YoutubeVideoUploadService.initializeUpload: Start.
17.12.21 16:09:08.464: YoutubeVideoUploadService.initializeUploadAsync: Requesting new upload/new resumable session uri.
17.12.21 16:09:08.474: YoutubeVideoUploadService.requestNewUpload: Start.
17.12.21 16:09:08.479: YoutubeVideoUploadService.requestNewUpload: New upload/new resumable session uri request content: {"snippet":{"title":"第二","description":"","tags":[],"defaultAudioLanguage":null,"defaultLanguage":null,"categoryId":null},"status":{"privacyStatus":"public"}}.
17.12.21 16:09:08.481: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:09:08.493: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:10:48.548: YoutubeVideoUploadService.requestNewUpload: Exception: System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.CancellationToken.ThrowIfCancellationRequested()
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|182_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Drexel.VidUp.Youtube.AuthenticationService.YoutubeAuthentication.GetNewAccessTokenAsync(YoutubeAccount youtubeAccount)
   at Drexel.VidUp.Youtube.HttpHelper.ensureAccessTokenAsync(YoutubeAccount youtubeAccount)
   at Drexel.VidUp.Youtube.HttpHelper.GetAuthenticatedRequestMessageAsync(YoutubeAccount youtubeAccount, HttpMethod method, String uri)
   at Drexel.VidUp.Youtube.VideoUploadService.YoutubeVideoUploadService.requestNewUploadAsync(Upload upload, AutoResetEvent resetEvent).
17.12.21 16:10:53.568: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:10:53.568: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:10:58.645: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:10:58.645: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:10:58.732: YoutubeVideoUploadService.requestNewUpload: End, failed 3 times.
17.12.21 16:10:58.753: Uploader.Upload: End.
17.12.21 16:10:58.781: MainWindowViewModel.doPostUploadAction: Start.
17.12.21 16:10:58.781: MainWindowViewModel.doPostUploadAction: No post upload action to perform.
17.12.21 16:10:58.782: MainWindowViewModel.doPostUploadAction: No data was sent during upload session.
17.12.21 16:11:08.795: MainWindowViewModel.doPostUploadAction: End.
17.12.21 16:13:23.352: Uploader.Upload: Start with resumeUploads: True, maxUploadInBytesPerSecond: 0.
17.12.21 16:13:23.353: YoutubeVideoUploadService.Upload: Start with upload: F:\常用软件\新建文件夹 (3)\第二TD.flv, maxUploadInBytesPerSecond: 0.
17.12.21 16:13:23.354: YoutubeVideoUploadService.Upload: Initialize upload.
17.12.21 16:13:23.354: YoutubeVideoUploadService.initializeUpload: Start.
17.12.21 16:13:23.354: YoutubeVideoUploadService.initializeUploadAsync: Requesting new upload/new resumable session uri.
17.12.21 16:13:23.354: YoutubeVideoUploadService.requestNewUpload: Start.
17.12.21 16:13:23.354: YoutubeVideoUploadService.requestNewUpload: New upload/new resumable session uri request content: {"snippet":{"title":"第二","description":"","tags":[],"defaultAudioLanguage":null,"defaultLanguage":null,"categoryId":null},"status":{"privacyStatus":"public"}}.
17.12.21 16:13:23.354: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:13:23.354: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:13:28.435: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:13:28.436: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:13:33.528: YoutubeVideoUploadService.requestNewUpload: Requesting new upload.
17.12.21 16:13:33.528: YoutubeAuthentication.GetNewAccessTokenAsync: Start.
17.12.21 16:13:33.610: YoutubeVideoUploadService.requestNewUpload: End, failed 3 times.
17.12.21 16:13:33.629: Uploader.Upload: End.
17.12.21 16:13:33.629: MainWindowViewModel.doPostUploadAction: Start.
17.12.21 16:13:33.629: MainWindowViewModel.doPostUploadAction: No post upload action to perform.
17.12.21 16:13:33.629: MainWindowViewModel.doPostUploadAction: No data was sent during upload session.
17.12.21 16:13:43.642: MainWindowViewModel.doPostUploadAction: End.

**Comment by Drexel2k** [comment]
It still looks somehow like a connection problem for me. Unfortunately I noticed that some error messages are not logged correctly, that is also the case in your log. I have to fix that in a future version...

I see that the problem occurs on authentication. The endpoint for accesss tokens is https://www.googleapis.com/oauth2/v4/token, can you try to ping www.googleapis.com ?

You can also try to completely reauthenticate VidUp by going to Settings->YouTube Account-> 3 dots menu and press the sign in button again, but I don't think it will help much.

**Comment by khmerifix** [comment]
hello brother, Can't Upload Fail

**Comment by Drexel2k** [comment]
Aren't you the guy who wanted to sell the app under it's own name without crediting me for the original creation and without publishing the source etc how it GPL requires?

Anyway, the amount of information you provide is too much to help you...

**Comment by khmerifix** [comment]
Why? I do not know anything

**Comment by Drexel2k** [comment]
No further information.
